### ISSUE TITLE
Exporting scene with terrain is not working

### ISSUE THREAD

**Issue by fenos** [BabylonJS/BabylonToolkit#58]
Hello,

I have created a simple scene with an empty terrain.
The project compiles just fine, however when i open the project in the browser, i get a OOM error from ammo.js

```
Uncaught (in promise) Error: abort(OOM). Build with -s ASSERTIONS=1 for more info.
    at qa (ammo.js:71:205)
    at e (ammo.js:82:87)
    at wb (ammo.js:42:38061)
    at af (ammo.js:26:127065)
    at Array.Ly (ammo.js:54:21199)
    at Array.My (ammo.js:50:7701)
    at yk (ammo.js:26:698603)
    at Su (ammo.js:34:13985)
    at HD.addTriangleNormals (ammo.js:703:331)
    at n.AddMeshVerts (babylon.manager.js:4:20808)
```

If i remove the terrain everything works just fine

**Comment by MackeyK24** [comment]
Terrains (and terrain collision) are a feature of the Pro version (When it is released)
